import os

POSTGRES_USER = 'postgres'
POSTGRES_PASSWORD = 'qwe'
POSTGRES_DB = 'invest2'
POSTGRES_HOST = 'localhost'
POSTGRES_PORT = '5432'

SQLALCHEMY_DATABASE_URI = f'postgresql+psycopg2://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}'
SQLALCHEMY_TRACK_MODIFICATIONS = False
